name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md  # Uncomment if you have a changelog
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: windows-latest  # Changed to windows-latest since this is a Windows executable
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # Binary name to build and upload
          bin: winddcutil_rs
          # GitHub token for uploading assets to GitHub Releases
          token: ${{ secrets.GITHUB_TOKEN }}
          # Build for Windows
          target: x86_64-pc-windows-msvc
          # Windows binaries typically use .exe extension
          archive: $bin-$tag-$target 